apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
name: docker-credential-acr-env
version: 0.0.3
appVersion: 0.0.3
sources:
  - https://github.com/jenkins-x/docker-credential-acr-env.git
